### ISSUE TITLE
Text Widget Bullet Points do not align with Location Widget Bullet Points

### ISSUE THREAD

**Issue by taija** [BellevueCollege/bc-douglas-fir-department-theme#5]
## Steps to Repro:
1. Insert a Location widget and add content
2. Insert a Text widget, and add bullet points

Text widget bullet points are much more indented than the ones in the location widget

![Image](https://github.com/BellevueCollege/bc-douglas-fir-department-theme/assets/5297534/d1b4944f-dcba-4933-953a-c8c1ca9d184c)

Related TDX ticket: https://bellevuecollege.teamdynamix.com/TDNext/Apps/409/Tickets/TicketDet.aspx?TicketID=24915376

**Comment by efuenzalida52** [comment]
Looks good!
